sudo: false
dist: bionic
language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38,lint,pypi-description,coverage-report
        - python: 3.9
          env: TOXENV=py39
install: pip install tox
script: tox
